SECTOR_CONFIGS = {
    "it_ites": {
        "name": "Technology & Information Services",
        "target_designations": ["CTO", "VP Engineering", "IT Manager", "Head of Digital", "CDO"],
        "company_size_focus": ["medium", "large", "enterprise"],
        "pain_points": [
            "Scaling engineering teams",
            "Reducing cloud infrastructure costs",
            "Modernising legacy systems",
            "Cybersecurity compliance",
            "Talent retention",
        ],
        "value_props": [
            "ROI within first quarter",
            "Reduces engineering overhead",
            "Integrates with existing stack",
        ],
        "best_outreach_days": ["Tuesday", "Wednesday", "Thursday"],
        "best_outreach_time": "9am-11am IST",
        "email_tone": "peer-to-peer technical",
        "avg_deal_cycle_days": 45,
        "avg_deal_value_inr": 500000,
    },
    "agriculture": {
        "name": "Agriculture & Allied Sectors",
        "target_designations": [
            "Farm Owner",
            "Agri Business Manager",
            "Supply Chain Head",
            "Procurement Manager",
            "CEO – Agri Co-op",
        ],
        "company_size_focus": ["small", "medium"],
        "pain_points": [
            "Weather and yield unpredictability",
            "Supply chain wastage",
            "Access to credit and insurance",
            "Market price volatility",
            "Cold chain logistics",
        ],
        "value_props": [
            "Increases farm yield by X%",
            "Reduces post-harvest loss",
            "Direct market access",
        ],
        "best_outreach_days": ["Monday", "Tuesday"],
        "best_outreach_time": "8am-10am IST",
        "email_tone": "consultative and empathetic",
        "avg_deal_cycle_days": 30,
        "avg_deal_value_inr": 150000,
    },
    "manufacturing": {
        "name": "Manufacturing Companies",
        "target_designations": [
            "Plant Head",
            "Operations Manager",
            "GM – Manufacturing",
            "Quality Head",
            "MD / CEO",
        ],
        "company_size_focus": ["small", "medium", "large"],
        "pain_points": [
            "Production downtime",
            "Quality control failures",
            "Raw material cost volatility",
            "Skilled labour shortage",
            "Export compliance complexity",
        ],
        "value_props": [
            "Reduces downtime by X%",
            "Improves OEE scores",
            "Automates quality checks",
        ],
        "best_outreach_days": ["Monday", "Wednesday", "Friday"],
        "best_outreach_time": "10am-12pm IST",
        "email_tone": "results-focused and direct",
        "avg_deal_cycle_days": 60,
        "avg_deal_value_inr": 750000,
    },
    "education": {
        "name": "Education — Schools, Colleges & Training",
        "target_designations": [
            "Principal",
            "Director",
            "Dean",
            "Head of Academics",
            "Training Manager",
            "Registrar",
        ],
        "company_size_focus": ["small", "medium"],
        "pain_points": [
            "Student engagement and retention",
            "Administrative workload",
            "Placement outcomes",
            "Accreditation compliance (NAAC, NBA)",
            "Digital transformation of classrooms",
        ],
        "value_props": [
            "Improves student pass rates",
            "Reduces admin overhead by 40%",
            "NAAC/NBA report automation",
        ],
        "best_outreach_days": ["Tuesday", "Wednesday", "Thursday"],
        "best_outreach_time": "9am-11am IST",
        "email_tone": "professional and benefit-led",
        "avg_deal_cycle_days": 30,
        "avg_deal_value_inr": 200000,
    },
    "marketing_media": {
        "name": "Marketing, Media & Services",
        "target_designations": [
            "CMO",
            "Marketing Head",
            "Brand Manager",
            "Media Director",
            "Agency Founder",
        ],
        "company_size_focus": ["micro", "small", "medium"],
        "pain_points": [
            "Proving ROI on campaigns",
            "Content production at scale",
            "Managing multiple client accounts",
            "Attribution and analytics",
            "Rising digital ad costs",
        ],
        "value_props": [
            "10x content output",
            "Real-time campaign analytics",
            "Client reporting automation",
        ],
        "best_outreach_days": ["Wednesday", "Thursday"],
        "best_outreach_time": "11am-1pm IST",
        "email_tone": "creative and punchy",
        "avg_deal_cycle_days": 21,
        "avg_deal_value_inr": 180000,
    },
    "finance_professional": {
        "name": "Finance & Professional Services",
        "target_designations": [
            "CFO",
            "Finance Director",
            "CA Partner",
            "Compliance Officer",
            "Risk Manager",
            "Managing Partner",
        ],
        "company_size_focus": ["small", "medium", "large"],
        "pain_points": [
            "Regulatory compliance burden",
            "Manual reconciliation and reporting",
            "Fraud detection and prevention",
            "Client onboarding KYC complexity",
            "Data security and audit trails",
        ],
        "value_props": [
            "Reduces compliance risk",
            "Automates reconciliation",
            "RBI/SEBI compliance-ready",
        ],
        "best_outreach_days": ["Tuesday", "Thursday"],
        "best_outreach_time": "9am-11am IST",
        "email_tone": "formal and trust-building",
        "avg_deal_cycle_days": 75,
        "avg_deal_value_inr": 600000,
    },
    "construction_real_estate": {
        "name": "Construction & Real Estate",
        "target_designations": [
            "Project Director",
            "MD",
            "CEO",
            "Site Manager",
            "Head of Procurement",
        ],
        "company_size_focus": ["small", "medium", "large"],
        "pain_points": [
            "Project delays and cost overruns",
            "Labour management at scale",
            "Material procurement inefficiencies",
            "RERA compliance",
            "Cash flow management",
        ],
        "value_props": [
            "Reduces project delays",
            "Streamlines procurement",
            "RERA-compliant reporting",
        ],
        "best_outreach_days": ["Monday", "Tuesday", "Wednesday"],
        "best_outreach_time": "9am-11am IST",
        "email_tone": "direct and ROI-focused",
        "avg_deal_cycle_days": 60,
        "avg_deal_value_inr": 800000,
    },
    "retail_ecommerce": {
        "name": "Retail & E-commerce",
        "target_designations": [
            "Head of E-commerce",
            "CMO",
            "Operations Director",
            "Category Manager",
            "COO",
        ],
        "company_size_focus": ["micro", "small", "medium"],
        "pain_points": [
            "Customer acquisition cost",
            "Cart abandonment",
            "Inventory management",
            "Last-mile delivery",
            "Competing with marketplaces",
        ],
        "value_props": [
            "Increases conversion rate",
            "Reduces CAC by X%",
            "AI-powered inventory forecasting",
        ],
        "best_outreach_days": ["Tuesday", "Wednesday"],
        "best_outreach_time": "10am-12pm IST",
        "email_tone": "data-driven and growth-focused",
        "avg_deal_cycle_days": 21,
        "avg_deal_value_inr": 250000,
    },
    "energy_utilities": {
        "name": "Energy & Utilities",
        "target_designations": [
            "Plant Manager",
            "Operations Head",
            "Energy Manager",
            "Director – Projects",
            "CEO",
        ],
        "company_size_focus": ["medium", "large", "enterprise"],
        "pain_points": [
            "Energy efficiency and cost reduction",
            "Renewable transition complexity",
            "Grid reliability and downtime",
            "Regulatory compliance (CEA, MNRE)",
            "Asset lifecycle management",
        ],
        "value_props": [
            "Reduces energy costs by X%",
            "MNRE/CEA compliant",
            "Predictive maintenance",
        ],
        "best_outreach_days": ["Monday", "Wednesday", "Thursday"],
        "best_outreach_time": "9am-11am IST",
        "email_tone": "technical and authoritative",
        "avg_deal_cycle_days": 90,
        "avg_deal_value_inr": 1200000,
    },
}


def get_sector_config(sector_code: str) -> dict | None:
    """Return the configuration dict for a given sector code, or None."""
    return SECTOR_CONFIGS.get(sector_code)


def get_all_sector_codes() -> list[str]:
    """Return all available sector codes."""
    return list(SECTOR_CONFIGS.keys())
